### ISSUE TITLE
0.0.8 not compatible with Restify 5.0.0

### ISSUE THREAD

**Issue by eddieajau** [TabDigital/restify-cors-middleware#34]
Restify 5 has dropped the `ALLOW_HEADERS` property. In fact it's dropped CORS altogether.

```
TypeError: Cannot read property 'ALLOW_HEADERS' of undefined
    at Object.<anonymous> (/node_modules/restify-cors-middleware/src/preflight.js:15:41)
```

Do you want a PR to change the offending line changed to perhaps:

```javascript
var DEFAULT_ALLOW_HEADERS = [];
```

then then bump your library to `0.1.0`? Or do you want something compatible with both Restify 4 and 5?

Thanks in advance.

**Comment by rprieto** [comment]
Hi, I just pushed `restify-cors-middleware@1.0.0` which should be compatible with Restify 4 and 5. Thanks!
